/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.pontodigital.view;

import javax.swing.JInternalFrame;

/**
 *
 * @author Neto
 */
public class GUIMenu extends javax.swing.JFrame {

    public GUIMenu() {
        initComponents();
        // Cadastrar
        jInternalFrameCadastrarFuncionario.setVisible(false);
        jInternalFrameCadastrarCategoria.setVisible(false);
        jInternalFrameCadastrarDepartamento.setVisible(false);
        jInternalFrameCadastrarEscala.setVisible(false);
        jInternalFrameVisualizarCadastro.setVisible(false);
        
        // Editar
        jInternalFrameEditarFuncionario.setVisible(false);
        jInternalFrameEditarCategoria.setVisible(false);
        jInternalFrameEditarDepartamento.setVisible(false);
        
        // Pesquisar
        jInternalFramePesquisarFuncionario.setVisible(false);
        jInternalFramePesquisarCategoria.setVisible(false);
        jInternalFramePesquisarDepartamento.setVisible(false);
        jInternalFramePesquisarEscala.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        jDesktopPanePrincipal = new javax.swing.JDesktopPane();
        jInternalFrameCadastrarFuncionario = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxCadastrarFuncionarioDepartamento = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxCadastrarFuncionarioCategoria = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldCadastrarFuncionarioNome = new javax.swing.JTextField();
        jTextFieldCadastrarFuncionarioTelefone = new javax.swing.JTextField();
        jTextFieldCadastrarFuncionarioCpf = new javax.swing.JTextField();
        jTextFieldCadastrarFuncionarioDataAdmissao = new javax.swing.JTextField();
        jToggleButtonCadastrarFuncionarioCadastrar = new javax.swing.JToggleButton();
        jToggleButtonCadastrarFuncionarioCancelar = new javax.swing.JToggleButton();
        jInternalFrameCadastrarCategoria = new javax.swing.JInternalFrame();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldCadastrarCargo = new javax.swing.JTextField();
        jToggleButtonCadastrarCategoria = new javax.swing.JToggleButton();
        jToggleButtonCancelarCadastrarCategoria = new javax.swing.JToggleButton();
        jLabel11 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jInternalFrameCadastrarDepartamento = new javax.swing.JInternalFrame();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldCadastrarDepartamento = new javax.swing.JTextField();
        jToggleButtonCadastrarDepartamento = new javax.swing.JToggleButton();
        jToggleButtonCancelarCadastrarDepartamento = new javax.swing.JToggleButton();
        jInternalFrameCadastrarEscala = new javax.swing.JInternalFrame();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldCadastrarEscala = new javax.swing.JTextField();
        jToggleButtonCadastrarEscala = new javax.swing.JToggleButton();
        jToggleButtonCancelarCadastrarEscala = new javax.swing.JToggleButton();
        jSpinnerHorasTrabalhadas = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        jInternalFrameVisualizarCadastro = new javax.swing.JInternalFrame();
        jLabel10 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jInternalFrameEditarFuncionario = new javax.swing.JInternalFrame();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jComboBoxEditarFuncionarioDepartamento = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        jComboBoxEditarFuncionarioCategoria = new javax.swing.JComboBox();
        jLabel21 = new javax.swing.JLabel();
        jTextFieldEditarFuncionarioNome = new javax.swing.JTextField();
        jTextFieldEditarFuncionarioTelefone = new javax.swing.JTextField();
        jTextFieldEditarFuncionarioCpf = new javax.swing.JTextField();
        jTextFieldEditarFuncionarioDataAdmissao = new javax.swing.JTextField();
        jToggleButtonEditarFuncionarioCadastrar = new javax.swing.JToggleButton();
        jToggleButtonEditarFuncionarioCancelar = new javax.swing.JToggleButton();
        jInternalFrameEditarCategoria = new javax.swing.JInternalFrame();
        jLabel22 = new javax.swing.JLabel();
        jTextFieldEditarCargo = new javax.swing.JTextField();
        jToggleButtonEditarCategoriaCadastrar = new javax.swing.JToggleButton();
        jToggleButtonCancelarEditarCategoriaCancelar = new javax.swing.JToggleButton();
        jLabel23 = new javax.swing.JLabel();
        jComboBoxEditarEscala = new javax.swing.JComboBox();
        jInternalFrameEditarDepartamento = new javax.swing.JInternalFrame();
        jLabel25 = new javax.swing.JLabel();
        jTextFieldEditarDepartamento = new javax.swing.JTextField();
        jToggleButtonEditarDepartamentoCadastrar = new javax.swing.JToggleButton();
        jToggleButtonCancelarEditarDepartamentoCancelar = new javax.swing.JToggleButton();
        jInternalFramePesquisarFuncionario = new javax.swing.JInternalFrame();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldPesquisarFuncionarioNome = new javax.swing.JTextField();
        jTextFieldPesquisarFuncionarioCpf = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jComboBoxPesquisarFuncionarioCategoria = new javax.swing.JComboBox();
        jButtonPesquisarFuncionarioPesquisar = new javax.swing.JButton();
        jButtonPesquisarFuncionarioCancelar = new javax.swing.JButton();
        jInternalFramePesquisarCategoria = new javax.swing.JInternalFrame();
        jLabel24 = new javax.swing.JLabel();
        jComboBoxPesquisarCategoriaSelecionar = new javax.swing.JComboBox<>();
        jButtonPesquisarCategoriaEditar = new javax.swing.JButton();
        jButtonPesquisarCategoriaCancelar = new javax.swing.JButton();
        jInternalFramePesquisarDepartamento = new javax.swing.JInternalFrame();
        jLabel26 = new javax.swing.JLabel();
        jComboBoxPesquisarDepartamentoSelecionar = new javax.swing.JComboBox<>();
        jButtonPesquisarDepartamentoEditar = new javax.swing.JButton();
        jButtonPesquisarDepartamentoCancelar = new javax.swing.JButton();
        jInternalFramePesquisarEscala = new javax.swing.JInternalFrame();
        jLabel27 = new javax.swing.JLabel();
        jComboBoxPesquisarEscalaSelecionar = new javax.swing.JComboBox<>();
        jButtonPesquisarEscalaEditar = new javax.swing.JButton();
        jButtonPesquisarEscalaCancelar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemCadastrarFuncionario = new javax.swing.JMenuItem();
        jMenuItemCadastrarCategoria = new javax.swing.JMenuItem();
        jMenuItemCadastrarDepartamento = new javax.swing.JMenuItem();
        jMenuItemCadastrarEscala = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItemEditarFuncionario = new javax.swing.JMenuItem();
        jMenuItemEditarCategoria = new javax.swing.JMenuItem();
        jMenuItemEditarDepartamento = new javax.swing.JMenuItem();
        jMenuItemEditarEscala = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItemListarFuncionariosGeral = new javax.swing.JMenuItem();
        jMenuItemListarFuncionariosPorCategoria = new javax.swing.JMenuItem();
        jMenuItemListarFuncionariosPorDepartamento = new javax.swing.JMenuItem();
        jMenuItemListarFuncionariosPorIdade = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemDesligarFuncionario = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemRelatorioDiario = new javax.swing.JMenuItem();
        jMenuItemRelatorioSemanal = new javax.swing.JMenuItem();
        jMenuItemRelatorioMensal = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ponto Digital - Menu");

        jPanelPrincipal.setLayout(null);

        jDesktopPanePrincipal.setBackground(new java.awt.Color(240, 240, 240));

        jInternalFrameCadastrarFuncionario.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Cadastrar Funcionário"));
        jInternalFrameCadastrarFuncionario.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        jInternalFrameCadastrarFuncionario.setTitle("Cadastrar Funcionário");
        jInternalFrameCadastrarFuncionario.setVisible(true);
        jInternalFrameCadastrarFuncionario.getContentPane().setLayout(null);

        jLabel1.setText("Nome:");
        jInternalFrameCadastrarFuncionario.getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 20, 90, 14);

        jLabel2.setText("Telefone:");
        jInternalFrameCadastrarFuncionario.getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 50, 100, 14);

        jLabel3.setText("Cpf:");
        jInternalFrameCadastrarFuncionario.getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 80, 80, 14);

        jLabel4.setText("Departamento: ");
        jInternalFrameCadastrarFuncionario.getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 110, 110, 14);

        jComboBoxCadastrarFuncionarioDepartamento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxCadastrarFuncionarioDepartamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jInternalFrameCadastrarFuncionario.getContentPane().add(jComboBoxCadastrarFuncionarioDepartamento);
        jComboBoxCadastrarFuncionarioDepartamento.setBounds(140, 100, 170, 21);

        jLabel5.setText("Categoria:");
        jInternalFrameCadastrarFuncionario.getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 140, 80, 14);

        jComboBoxCadastrarFuncionarioCategoria.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxCadastrarFuncionarioCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jInternalFrameCadastrarFuncionario.getContentPane().add(jComboBoxCadastrarFuncionarioCategoria);
        jComboBoxCadastrarFuncionarioCategoria.setBounds(140, 130, 170, 21);

        jLabel6.setText("Data de Admissão: ");
        jInternalFrameCadastrarFuncionario.getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 170, 120, 14);

        jTextFieldCadastrarFuncionarioNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldCadastrarFuncionarioNome.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jInternalFrameCadastrarFuncionario.getContentPane().add(jTextFieldCadastrarFuncionarioNome);
        jTextFieldCadastrarFuncionarioNome.setBounds(140, 10, 170, 23);

        jTextFieldCadastrarFuncionarioTelefone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jInternalFrameCadastrarFuncionario.getContentPane().add(jTextFieldCadastrarFuncionarioTelefone);
        jTextFieldCadastrarFuncionarioTelefone.setBounds(140, 40, 170, 21);

        jTextFieldCadastrarFuncionarioCpf.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jInternalFrameCadastrarFuncionario.getContentPane().add(jTextFieldCadastrarFuncionarioCpf);
        jTextFieldCadastrarFuncionarioCpf.setBounds(140, 70, 170, 21);

        jTextFieldCadastrarFuncionarioDataAdmissao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jInternalFrameCadastrarFuncionario.getContentPane().add(jTextFieldCadastrarFuncionarioDataAdmissao);
        jTextFieldCadastrarFuncionarioDataAdmissao.setBounds(140, 160, 170, 20);

        jToggleButtonCadastrarFuncionarioCadastrar.setText("Cadastrar");
        jInternalFrameCadastrarFuncionario.getContentPane().add(jToggleButtonCadastrarFuncionarioCadastrar);
        jToggleButtonCadastrarFuncionarioCadastrar.setBounds(80, 210, 105, 23);

        jToggleButtonCadastrarFuncionarioCancelar.setText("Cancelar");
        jToggleButtonCadastrarFuncionarioCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonCadastrarFuncionarioCancelarActionPerformed(evt);
            }
        });
        jInternalFrameCadastrarFuncionario.getContentPane().add(jToggleButtonCadastrarFuncionarioCancelar);
        jToggleButtonCadastrarFuncionarioCancelar.setBounds(210, 210, 105, 23);

        jInternalFrameCadastrarCategoria.setTitle("Cadastrar Categoria");
        jInternalFrameCadastrarCategoria.setVisible(true);
        jInternalFrameCadastrarCategoria.getContentPane().setLayout(null);

        jLabel7.setText("Nome do Categoria: ");
        jInternalFrameCadastrarCategoria.getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 20, 120, 14);
        jInternalFrameCadastrarCategoria.getContentPane().add(jTextFieldCadastrarCargo);
        jTextFieldCadastrarCargo.setBounds(130, 20, 170, 20);

        jToggleButtonCadastrarCategoria.setText("Cadastrar");
        jInternalFrameCadastrarCategoria.getContentPane().add(jToggleButtonCadastrarCategoria);
        jToggleButtonCadastrarCategoria.setBounds(80, 90, 105, 23);

        jToggleButtonCancelarCadastrarCategoria.setText("Cancelar");
        jToggleButtonCancelarCadastrarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonCancelarCadastrarCategoriaActionPerformed(evt);
            }
        });
        jInternalFrameCadastrarCategoria.getContentPane().add(jToggleButtonCancelarCadastrarCategoria);
        jToggleButtonCancelarCadastrarCategoria.setBounds(200, 90, 100, 23);

        jLabel11.setText("Escala:");
        jInternalFrameCadastrarCategoria.getContentPane().add(jLabel11);
        jLabel11.setBounds(10, 50, 100, 14);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jInternalFrameCadastrarCategoria.getContentPane().add(jComboBox3);
        jComboBox3.setBounds(130, 50, 170, 20);

        jInternalFrameCadastrarDepartamento.setTitle("Cadastrar Departamento");
        jInternalFrameCadastrarDepartamento.setVisible(true);

        jLabel8.setText("Nome do Cargo: ");

        jToggleButtonCadastrarDepartamento.setText("Cadastrar");

        jToggleButtonCancelarCadastrarDepartamento.setText("Cancelar");
        jToggleButtonCancelarCadastrarDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonCancelarCadastrarDepartamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrameCadastrarDepartamentoLayout = new javax.swing.GroupLayout(jInternalFrameCadastrarDepartamento.getContentPane());
        jInternalFrameCadastrarDepartamento.getContentPane().setLayout(jInternalFrameCadastrarDepartamentoLayout);
        jInternalFrameCadastrarDepartamentoLayout.setHorizontalGroup(
            jInternalFrameCadastrarDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameCadastrarDepartamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrameCadastrarDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrameCadastrarDepartamentoLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jToggleButtonCadastrarDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jToggleButtonCancelarCadastrarDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrameCadastrarDepartamentoLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jTextFieldCadastrarDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrameCadastrarDepartamentoLayout.setVerticalGroup(
            jInternalFrameCadastrarDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameCadastrarDepartamentoLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jInternalFrameCadastrarDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldCadastrarDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jInternalFrameCadastrarDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButtonCadastrarDepartamento)
                    .addComponent(jToggleButtonCancelarCadastrarDepartamento))
                .addContainerGap(400, Short.MAX_VALUE))
        );

        jInternalFrameCadastrarEscala.setTitle("Cadastrar Escala");
        jInternalFrameCadastrarEscala.setVisible(true);

        jLabel9.setText("Nome do Escala: ");

        jToggleButtonCadastrarEscala.setText("Cadastrar");

        jToggleButtonCancelarCadastrarEscala.setText("Cancelar");
        jToggleButtonCancelarCadastrarEscala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonCancelarCadastrarEscalaActionPerformed(evt);
            }
        });

        jLabel12.setText("Horas Trabalhadas:   ");

        javax.swing.GroupLayout jInternalFrameCadastrarEscalaLayout = new javax.swing.GroupLayout(jInternalFrameCadastrarEscala.getContentPane());
        jInternalFrameCadastrarEscala.getContentPane().setLayout(jInternalFrameCadastrarEscalaLayout);
        jInternalFrameCadastrarEscalaLayout.setHorizontalGroup(
            jInternalFrameCadastrarEscalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameCadastrarEscalaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrameCadastrarEscalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jInternalFrameCadastrarEscalaLayout.createSequentialGroup()
                        .addGroup(jInternalFrameCadastrarEscalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jInternalFrameCadastrarEscalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSpinnerHorasTrabalhadas, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                            .addComponent(jTextFieldCadastrarEscala)))
                    .addGroup(jInternalFrameCadastrarEscalaLayout.createSequentialGroup()
                        .addComponent(jToggleButtonCadastrarEscala, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jToggleButtonCancelarCadastrarEscala, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrameCadastrarEscalaLayout.setVerticalGroup(
            jInternalFrameCadastrarEscalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameCadastrarEscalaLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jInternalFrameCadastrarEscalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldCadastrarEscala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrameCadastrarEscalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerHorasTrabalhadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrameCadastrarEscalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButtonCadastrarEscala)
                    .addComponent(jToggleButtonCancelarCadastrarEscala))
                .addContainerGap(267, Short.MAX_VALUE))
        );

        jInternalFrameVisualizarCadastro.setVisible(true);

        jLabel10.setText("Selecione o tipo de Cadastro: ");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jInternalFrameVisualizarCadastroLayout = new javax.swing.GroupLayout(jInternalFrameVisualizarCadastro.getContentPane());
        jInternalFrameVisualizarCadastro.getContentPane().setLayout(jInternalFrameVisualizarCadastroLayout);
        jInternalFrameVisualizarCadastroLayout.setHorizontalGroup(
            jInternalFrameVisualizarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameVisualizarCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(157, Short.MAX_VALUE))
        );
        jInternalFrameVisualizarCadastroLayout.setVerticalGroup(
            jInternalFrameVisualizarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameVisualizarCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrameVisualizarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(377, Short.MAX_VALUE))
        );

        jInternalFrameEditarFuncionario.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Editar Funcionário"));
        jInternalFrameEditarFuncionario.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        jInternalFrameEditarFuncionario.setTitle("Editar Funcionário");
        jInternalFrameEditarFuncionario.setVisible(true);
        jInternalFrameEditarFuncionario.getContentPane().setLayout(null);

        jLabel16.setText("Nome:");
        jInternalFrameEditarFuncionario.getContentPane().add(jLabel16);
        jLabel16.setBounds(10, 20, 90, 14);

        jLabel17.setText("Telefone:");
        jInternalFrameEditarFuncionario.getContentPane().add(jLabel17);
        jLabel17.setBounds(10, 50, 100, 14);

        jLabel18.setText("Cpf:");
        jInternalFrameEditarFuncionario.getContentPane().add(jLabel18);
        jLabel18.setBounds(10, 80, 80, 14);

        jLabel19.setText("Departamento: ");
        jInternalFrameEditarFuncionario.getContentPane().add(jLabel19);
        jLabel19.setBounds(10, 110, 110, 14);

        jComboBoxEditarFuncionarioDepartamento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxEditarFuncionarioDepartamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jInternalFrameEditarFuncionario.getContentPane().add(jComboBoxEditarFuncionarioDepartamento);
        jComboBoxEditarFuncionarioDepartamento.setBounds(140, 100, 170, 21);

        jLabel20.setText("Categoria:");
        jInternalFrameEditarFuncionario.getContentPane().add(jLabel20);
        jLabel20.setBounds(10, 140, 80, 14);

        jComboBoxEditarFuncionarioCategoria.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxEditarFuncionarioCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jInternalFrameEditarFuncionario.getContentPane().add(jComboBoxEditarFuncionarioCategoria);
        jComboBoxEditarFuncionarioCategoria.setBounds(140, 130, 170, 21);

        jLabel21.setText("Data de Admissão: ");
        jInternalFrameEditarFuncionario.getContentPane().add(jLabel21);
        jLabel21.setBounds(10, 170, 120, 14);

        jTextFieldEditarFuncionarioNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldEditarFuncionarioNome.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jInternalFrameEditarFuncionario.getContentPane().add(jTextFieldEditarFuncionarioNome);
        jTextFieldEditarFuncionarioNome.setBounds(140, 10, 170, 23);

        jTextFieldEditarFuncionarioTelefone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jInternalFrameEditarFuncionario.getContentPane().add(jTextFieldEditarFuncionarioTelefone);
        jTextFieldEditarFuncionarioTelefone.setBounds(140, 40, 170, 21);

        jTextFieldEditarFuncionarioCpf.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jInternalFrameEditarFuncionario.getContentPane().add(jTextFieldEditarFuncionarioCpf);
        jTextFieldEditarFuncionarioCpf.setBounds(140, 70, 170, 21);

        jTextFieldEditarFuncionarioDataAdmissao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jInternalFrameEditarFuncionario.getContentPane().add(jTextFieldEditarFuncionarioDataAdmissao);
        jTextFieldEditarFuncionarioDataAdmissao.setBounds(140, 160, 170, 20);

        jToggleButtonEditarFuncionarioCadastrar.setText("Cadastrar");
        jInternalFrameEditarFuncionario.getContentPane().add(jToggleButtonEditarFuncionarioCadastrar);
        jToggleButtonEditarFuncionarioCadastrar.setBounds(80, 210, 105, 23);

        jToggleButtonEditarFuncionarioCancelar.setText("Cancelar");
        jToggleButtonEditarFuncionarioCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonEditarFuncionarioCancelarActionPerformed(evt);
            }
        });
        jInternalFrameEditarFuncionario.getContentPane().add(jToggleButtonEditarFuncionarioCancelar);
        jToggleButtonEditarFuncionarioCancelar.setBounds(210, 210, 105, 23);

        jInternalFrameEditarCategoria.setTitle("Editar Categoria");
        jInternalFrameEditarCategoria.setVisible(true);
        jInternalFrameEditarCategoria.getContentPane().setLayout(null);

        jLabel22.setText("Nome do Categoria: ");
        jInternalFrameEditarCategoria.getContentPane().add(jLabel22);
        jLabel22.setBounds(10, 20, 120, 14);
        jInternalFrameEditarCategoria.getContentPane().add(jTextFieldEditarCargo);
        jTextFieldEditarCargo.setBounds(130, 20, 170, 20);

        jToggleButtonEditarCategoriaCadastrar.setText("Cadastrar");
        jInternalFrameEditarCategoria.getContentPane().add(jToggleButtonEditarCategoriaCadastrar);
        jToggleButtonEditarCategoriaCadastrar.setBounds(80, 90, 105, 23);

        jToggleButtonCancelarEditarCategoriaCancelar.setText("Cancelar");
        jToggleButtonCancelarEditarCategoriaCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonCancelarEditarCategoriaCancelarActionPerformed(evt);
            }
        });
        jInternalFrameEditarCategoria.getContentPane().add(jToggleButtonCancelarEditarCategoriaCancelar);
        jToggleButtonCancelarEditarCategoriaCancelar.setBounds(200, 90, 100, 23);

        jLabel23.setText("Escala:");
        jInternalFrameEditarCategoria.getContentPane().add(jLabel23);
        jLabel23.setBounds(10, 50, 100, 14);

        jComboBoxEditarEscala.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jInternalFrameEditarCategoria.getContentPane().add(jComboBoxEditarEscala);
        jComboBoxEditarEscala.setBounds(130, 50, 170, 20);

        jInternalFrameEditarDepartamento.setTitle("Editar Departamento");
        jInternalFrameEditarDepartamento.setVisible(true);

        jLabel25.setText("Nome do Cargo: ");

        jToggleButtonEditarDepartamentoCadastrar.setText("Cadastrar");

        jToggleButtonCancelarEditarDepartamentoCancelar.setText("Cancelar");
        jToggleButtonCancelarEditarDepartamentoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonCancelarEditarDepartamentoCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrameEditarDepartamentoLayout = new javax.swing.GroupLayout(jInternalFrameEditarDepartamento.getContentPane());
        jInternalFrameEditarDepartamento.getContentPane().setLayout(jInternalFrameEditarDepartamentoLayout);
        jInternalFrameEditarDepartamentoLayout.setHorizontalGroup(
            jInternalFrameEditarDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameEditarDepartamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrameEditarDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrameEditarDepartamentoLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jToggleButtonEditarDepartamentoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jToggleButtonCancelarEditarDepartamentoCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrameEditarDepartamentoLayout.createSequentialGroup()
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jTextFieldEditarDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrameEditarDepartamentoLayout.setVerticalGroup(
            jInternalFrameEditarDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameEditarDepartamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrameEditarDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(jTextFieldEditarDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jInternalFrameEditarDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButtonEditarDepartamentoCadastrar)
                    .addComponent(jToggleButtonCancelarEditarDepartamentoCancelar))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jInternalFramePesquisarFuncionario.setTitle("Pesquisar Funcionário");
        jInternalFramePesquisarFuncionario.setVisible(true);

        jLabel13.setText("Nome:    ");

        jLabel14.setText("Cpf:       ");

        jLabel15.setText("Categoria:    ");

        jComboBoxPesquisarFuncionarioCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonPesquisarFuncionarioPesquisar.setText("Pesquisar");

        jButtonPesquisarFuncionarioCancelar.setText("Cancelar");
        jButtonPesquisarFuncionarioCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarFuncionarioCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFramePesquisarFuncionarioLayout = new javax.swing.GroupLayout(jInternalFramePesquisarFuncionario.getContentPane());
        jInternalFramePesquisarFuncionario.getContentPane().setLayout(jInternalFramePesquisarFuncionarioLayout);
        jInternalFramePesquisarFuncionarioLayout.setHorizontalGroup(
            jInternalFramePesquisarFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFramePesquisarFuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFramePesquisarFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFramePesquisarFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldPesquisarFuncionarioNome)
                    .addComponent(jTextFieldPesquisarFuncionarioCpf)
                    .addComponent(jComboBoxPesquisarFuncionarioCategoria, 0, 199, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFramePesquisarFuncionarioLayout.createSequentialGroup()
                .addContainerGap(170, Short.MAX_VALUE)
                .addComponent(jButtonPesquisarFuncionarioPesquisar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPesquisarFuncionarioCancelar)
                .addGap(11, 11, 11))
        );
        jInternalFramePesquisarFuncionarioLayout.setVerticalGroup(
            jInternalFramePesquisarFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFramePesquisarFuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFramePesquisarFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldPesquisarFuncionarioNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFramePesquisarFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextFieldPesquisarFuncionarioCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFramePesquisarFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jComboBoxPesquisarFuncionarioCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                .addGroup(jInternalFramePesquisarFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPesquisarFuncionarioPesquisar)
                    .addComponent(jButtonPesquisarFuncionarioCancelar))
                .addContainerGap())
        );

        jInternalFramePesquisarCategoria.setTitle("Pesquisar Categoria");
        jInternalFramePesquisarCategoria.setVisible(true);

        jLabel24.setText("Selecionar Categoria: ");

        jComboBoxPesquisarCategoriaSelecionar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonPesquisarCategoriaEditar.setText("Editar");
        jButtonPesquisarCategoriaEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarCategoriaEditarActionPerformed(evt);
            }
        });

        jButtonPesquisarCategoriaCancelar.setText("Cancelar");
        jButtonPesquisarCategoriaCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarCategoriaCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFramePesquisarCategoriaLayout = new javax.swing.GroupLayout(jInternalFramePesquisarCategoria.getContentPane());
        jInternalFramePesquisarCategoria.getContentPane().setLayout(jInternalFramePesquisarCategoriaLayout);
        jInternalFramePesquisarCategoriaLayout.setHorizontalGroup(
            jInternalFramePesquisarCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFramePesquisarCategoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFramePesquisarCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxPesquisarCategoriaSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFramePesquisarCategoriaLayout.createSequentialGroup()
                        .addComponent(jButtonPesquisarCategoriaEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonPesquisarCategoriaCancelar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFramePesquisarCategoriaLayout.setVerticalGroup(
            jInternalFramePesquisarCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFramePesquisarCategoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFramePesquisarCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jComboBoxPesquisarCategoriaSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFramePesquisarCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPesquisarCategoriaCancelar)
                    .addComponent(jButtonPesquisarCategoriaEditar))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jInternalFramePesquisarDepartamento.setTitle("Pesquisar Departamento");
        jInternalFramePesquisarDepartamento.setToolTipText("");
        jInternalFramePesquisarDepartamento.setVisible(true);

        jLabel26.setText("Selecionar Departamento: ");

        jComboBoxPesquisarDepartamentoSelecionar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonPesquisarDepartamentoEditar.setText("Editar");
        jButtonPesquisarDepartamentoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarDepartamentoEditarActionPerformed(evt);
            }
        });

        jButtonPesquisarDepartamentoCancelar.setText("Cancelar");
        jButtonPesquisarDepartamentoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarDepartamentoCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFramePesquisarDepartamentoLayout = new javax.swing.GroupLayout(jInternalFramePesquisarDepartamento.getContentPane());
        jInternalFramePesquisarDepartamento.getContentPane().setLayout(jInternalFramePesquisarDepartamentoLayout);
        jInternalFramePesquisarDepartamentoLayout.setHorizontalGroup(
            jInternalFramePesquisarDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFramePesquisarDepartamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFramePesquisarDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxPesquisarDepartamentoSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFramePesquisarDepartamentoLayout.createSequentialGroup()
                        .addComponent(jButtonPesquisarDepartamentoEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonPesquisarDepartamentoCancelar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFramePesquisarDepartamentoLayout.setVerticalGroup(
            jInternalFramePesquisarDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFramePesquisarDepartamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFramePesquisarDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jComboBoxPesquisarDepartamentoSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFramePesquisarDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPesquisarDepartamentoCancelar)
                    .addComponent(jButtonPesquisarDepartamentoEditar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jInternalFramePesquisarEscala.setTitle("Pesquisar Escala");
        jInternalFramePesquisarEscala.setToolTipText("");
        jInternalFramePesquisarEscala.setVisible(true);

        jLabel27.setText("Selecionar Escala: ");

        jComboBoxPesquisarEscalaSelecionar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonPesquisarEscalaEditar.setText("Editar");
        jButtonPesquisarEscalaEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarEscalaEditarActionPerformed(evt);
            }
        });

        jButtonPesquisarEscalaCancelar.setText("Cancelar");
        jButtonPesquisarEscalaCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarEscalaCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFramePesquisarEscalaLayout = new javax.swing.GroupLayout(jInternalFramePesquisarEscala.getContentPane());
        jInternalFramePesquisarEscala.getContentPane().setLayout(jInternalFramePesquisarEscalaLayout);
        jInternalFramePesquisarEscalaLayout.setHorizontalGroup(
            jInternalFramePesquisarEscalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFramePesquisarEscalaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFramePesquisarEscalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxPesquisarEscalaSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFramePesquisarEscalaLayout.createSequentialGroup()
                        .addComponent(jButtonPesquisarEscalaEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonPesquisarEscalaCancelar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFramePesquisarEscalaLayout.setVerticalGroup(
            jInternalFramePesquisarEscalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFramePesquisarEscalaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFramePesquisarEscalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jComboBoxPesquisarEscalaSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFramePesquisarEscalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPesquisarEscalaCancelar)
                    .addComponent(jButtonPesquisarEscalaEditar))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jDesktopPanePrincipal.setLayer(jInternalFrameCadastrarFuncionario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPanePrincipal.setLayer(jInternalFrameCadastrarCategoria, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPanePrincipal.setLayer(jInternalFrameCadastrarDepartamento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPanePrincipal.setLayer(jInternalFrameCadastrarEscala, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPanePrincipal.setLayer(jInternalFrameVisualizarCadastro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPanePrincipal.setLayer(jInternalFrameEditarFuncionario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPanePrincipal.setLayer(jInternalFrameEditarCategoria, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPanePrincipal.setLayer(jInternalFrameEditarDepartamento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPanePrincipal.setLayer(jInternalFramePesquisarFuncionario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPanePrincipal.setLayer(jInternalFramePesquisarCategoria, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPanePrincipal.setLayer(jInternalFramePesquisarDepartamento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPanePrincipal.setLayer(jInternalFramePesquisarEscala, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPanePrincipalLayout = new javax.swing.GroupLayout(jDesktopPanePrincipal);
        jDesktopPanePrincipal.setLayout(jDesktopPanePrincipalLayout);
        jDesktopPanePrincipalLayout.setHorizontalGroup(
            jDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPanePrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPanePrincipalLayout.createSequentialGroup()
                        .addGroup(jDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jInternalFrameCadastrarDepartamento)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPanePrincipalLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jInternalFrameCadastrarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addComponent(jInternalFrameCadastrarEscala)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jInternalFrameCadastrarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(220, 220, 220))
                    .addGroup(jDesktopPanePrincipalLayout.createSequentialGroup()
                        .addComponent(jInternalFramePesquisarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jInternalFramePesquisarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jInternalFrameVisualizarCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPanePrincipalLayout.createSequentialGroup()
                    .addContainerGap(711, Short.MAX_VALUE)
                    .addComponent(jInternalFrameEditarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(200, 200, 200)))
            .addGroup(jDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPanePrincipalLayout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jInternalFrameEditarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(397, Short.MAX_VALUE)))
            .addGroup(jDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPanePrincipalLayout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jInternalFrameEditarDepartamento)
                    .addGap(763, 763, 763)))
            .addGroup(jDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPanePrincipalLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jInternalFramePesquisarDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(444, Short.MAX_VALUE)))
            .addGroup(jDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPanePrincipalLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jInternalFramePesquisarEscala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(483, Short.MAX_VALUE)))
        );
        jDesktopPanePrincipalLayout.setVerticalGroup(
            jDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPanePrincipalLayout.createSequentialGroup()
                .addGroup(jDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jInternalFrameVisualizarCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDesktopPanePrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jInternalFramePesquisarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jInternalFramePesquisarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPanePrincipalLayout.createSequentialGroup()
                        .addGroup(jDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jInternalFrameCadastrarDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jInternalFrameCadastrarEscala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jInternalFrameCadastrarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jDesktopPanePrincipalLayout.createSequentialGroup()
                        .addComponent(jInternalFrameCadastrarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113))))
            .addGroup(jDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPanePrincipalLayout.createSequentialGroup()
                    .addContainerGap(541, Short.MAX_VALUE)
                    .addComponent(jInternalFrameEditarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(347, 347, 347)))
            .addGroup(jDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPanePrincipalLayout.createSequentialGroup()
                    .addContainerGap(1035, Short.MAX_VALUE)
                    .addComponent(jInternalFrameEditarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)))
            .addGroup(jDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPanePrincipalLayout.createSequentialGroup()
                    .addContainerGap(883, Short.MAX_VALUE)
                    .addComponent(jInternalFrameEditarDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(154, 154, 154)))
            .addGroup(jDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPanePrincipalLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jInternalFramePesquisarDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1048, Short.MAX_VALUE)))
            .addGroup(jDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPanePrincipalLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jInternalFramePesquisarEscala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1056, Short.MAX_VALUE)))
        );

        jPanelPrincipal.add(jDesktopPanePrincipal);
        jDesktopPanePrincipal.setBounds(0, 0, 800, 580);

        jMenu1.setText("Cadastrar");

        jMenuItemCadastrarFuncionario.setText("Funcionário");
        jMenuItemCadastrarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastrarFuncionarioActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemCadastrarFuncionario);

        jMenuItemCadastrarCategoria.setText("Categoria");
        jMenuItemCadastrarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastrarCategoriaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemCadastrarCategoria);

        jMenuItemCadastrarDepartamento.setText("Departamento");
        jMenuItemCadastrarDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastrarDepartamentoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemCadastrarDepartamento);

        jMenuItemCadastrarEscala.setText("Escala");
        jMenuItemCadastrarEscala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastrarEscalaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemCadastrarEscala);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Editar");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        jMenuItemEditarFuncionario.setText("Funcionário");
        jMenuItemEditarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEditarFuncionarioActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemEditarFuncionario);

        jMenuItemEditarCategoria.setText("Categoria");
        jMenuItemEditarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEditarCategoriaActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemEditarCategoria);

        jMenuItemEditarDepartamento.setText("Departamento");
        jMenuItemEditarDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEditarDepartamentoActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemEditarDepartamento);

        jMenuItemEditarEscala.setText("Escala");
        jMenuItemEditarEscala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEditarEscalaActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemEditarEscala);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Visualizar");

        jMenuItemListarFuncionariosGeral.setText("Listar Funcionários Geral");
        jMenuItemListarFuncionariosGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListarFuncionariosGeralActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItemListarFuncionariosGeral);

        jMenuItemListarFuncionariosPorCategoria.setText("Listar Funcionários por Categoria");
        jMenu5.add(jMenuItemListarFuncionariosPorCategoria);

        jMenuItemListarFuncionariosPorDepartamento.setText("Listar Funcionários por Departamento");
        jMenu5.add(jMenuItemListarFuncionariosPorDepartamento);

        jMenuItemListarFuncionariosPorIdade.setText("Listar Funcionários por Idade");
        jMenu5.add(jMenuItemListarFuncionariosPorIdade);

        jMenuBar1.add(jMenu5);

        jMenu3.setText("Desligar");

        jMenuItemDesligarFuncionario.setText("Funcionário");
        jMenu3.add(jMenuItemDesligarFuncionario);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Relatórios");

        jMenuItemRelatorioDiario.setText("Diário");
        jMenu2.add(jMenuItemRelatorioDiario);

        jMenuItemRelatorioSemanal.setText("Semanal");
        jMenu2.add(jMenuItemRelatorioSemanal);

        jMenuItemRelatorioMensal.setText("Mensal");
        jMenuItemRelatorioMensal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRelatorioMensalActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemRelatorioMensal);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(816, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCadastrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastrarFuncionarioActionPerformed
        jInternalFrameCadastrarFuncionario.setVisible(true);
        jInternalFrameCadastrarCategoria.setVisible(false);
        jInternalFrameCadastrarDepartamento.setVisible(false);
        jInternalFrameCadastrarEscala.setVisible(false);
    }//GEN-LAST:event_jMenuItemCadastrarFuncionarioActionPerformed

    private void jMenuItemRelatorioMensalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRelatorioMensalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemRelatorioMensalActionPerformed

    private void jToggleButtonCadastrarFuncionarioCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonCadastrarFuncionarioCancelarActionPerformed
        jInternalFrameCadastrarFuncionario.setVisible(false);
    }//GEN-LAST:event_jToggleButtonCadastrarFuncionarioCancelarActionPerformed

    private void jToggleButtonCancelarCadastrarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonCancelarCadastrarCategoriaActionPerformed
        jInternalFrameCadastrarCategoria.setVisible(false);
    }//GEN-LAST:event_jToggleButtonCancelarCadastrarCategoriaActionPerformed

    private void jMenuItemCadastrarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastrarCategoriaActionPerformed
        jInternalFrameCadastrarCategoria.setVisible(true);
        jInternalFrameCadastrarDepartamento.setVisible(false);
        jInternalFrameCadastrarEscala.setVisible(false);
        jInternalFrameCadastrarFuncionario.setVisible(false);
    }//GEN-LAST:event_jMenuItemCadastrarCategoriaActionPerformed

    private void jToggleButtonCancelarCadastrarDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonCancelarCadastrarDepartamentoActionPerformed
        jInternalFrameCadastrarDepartamento.setVisible(false);
    }//GEN-LAST:event_jToggleButtonCancelarCadastrarDepartamentoActionPerformed

    private void jMenuItemCadastrarDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastrarDepartamentoActionPerformed
        jInternalFrameCadastrarDepartamento.setVisible(true);
        jInternalFrameCadastrarCategoria.setVisible(false);
        jInternalFrameCadastrarEscala.setVisible(false);
        jInternalFrameCadastrarFuncionario.setVisible(false);
    }//GEN-LAST:event_jMenuItemCadastrarDepartamentoActionPerformed

    private void jToggleButtonCancelarCadastrarEscalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonCancelarCadastrarEscalaActionPerformed
        jInternalFrameCadastrarEscala.setVisible(false);
    }//GEN-LAST:event_jToggleButtonCancelarCadastrarEscalaActionPerformed

    private void jMenuItemCadastrarEscalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastrarEscalaActionPerformed
        jInternalFrameCadastrarEscala.setVisible(true);
        jInternalFrameCadastrarFuncionario.setVisible(false);
        jInternalFrameCadastrarDepartamento.setVisible(false);
        jInternalFrameCadastrarCategoria.setVisible(false);
    }//GEN-LAST:event_jMenuItemCadastrarEscalaActionPerformed

    private void jMenuItemListarFuncionariosGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListarFuncionariosGeralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemListarFuncionariosGeralActionPerformed

    private void jMenuItemEditarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEditarFuncionarioActionPerformed
        jInternalFramePesquisarFuncionario.setVisible(true);
        //jInternalFrameEditarFuncionario.setVisible(true);
    }//GEN-LAST:event_jMenuItemEditarFuncionarioActionPerformed

    private void jButtonPesquisarFuncionarioCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarFuncionarioCancelarActionPerformed
        jInternalFramePesquisarFuncionario.setVisible(false);
    }//GEN-LAST:event_jButtonPesquisarFuncionarioCancelarActionPerformed

    private void jToggleButtonEditarFuncionarioCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonEditarFuncionarioCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonEditarFuncionarioCancelarActionPerformed

    private void jToggleButtonCancelarEditarCategoriaCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonCancelarEditarCategoriaCancelarActionPerformed
        jInternalFrameEditarCategoria.setVisible(false);
    }//GEN-LAST:event_jToggleButtonCancelarEditarCategoriaCancelarActionPerformed

    private void jMenuItemEditarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEditarCategoriaActionPerformed
        //jInternalFrameEditarCategoria.setVisible(true);
        jInternalFramePesquisarCategoria.setVisible(true);
    }//GEN-LAST:event_jMenuItemEditarCategoriaActionPerformed

    private void jButtonPesquisarCategoriaEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarCategoriaEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPesquisarCategoriaEditarActionPerformed

    private void jButtonPesquisarCategoriaCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarCategoriaCancelarActionPerformed
        // TODO add your handling code here:
        jInternalFramePesquisarCategoria.setVisible(false);
    }//GEN-LAST:event_jButtonPesquisarCategoriaCancelarActionPerformed

    private void jToggleButtonCancelarEditarDepartamentoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonCancelarEditarDepartamentoCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonCancelarEditarDepartamentoCancelarActionPerformed

    private void jButtonPesquisarDepartamentoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarDepartamentoEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPesquisarDepartamentoEditarActionPerformed

    private void jButtonPesquisarDepartamentoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarDepartamentoCancelarActionPerformed
        // TODO add your handling code here:
        jInternalFramePesquisarDepartamento.setVisible(false);
    }//GEN-LAST:event_jButtonPesquisarDepartamentoCancelarActionPerformed

    private void jMenuItemEditarDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEditarDepartamentoActionPerformed
        // TODO add your handling code here:
        jInternalFramePesquisarDepartamento.setVisible(true);
    }//GEN-LAST:event_jMenuItemEditarDepartamentoActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        // TODO add your handling code here:
        jInternalFramePesquisarDepartamento.setVisible(true);
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void jButtonPesquisarEscalaEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarEscalaEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPesquisarEscalaEditarActionPerformed

    private void jButtonPesquisarEscalaCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarEscalaCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPesquisarEscalaCancelarActionPerformed

    private void jMenuItemEditarEscalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEditarEscalaActionPerformed
        // TODO add your handling code here:
        jInternalFramePesquisarEscala.setVisible(true);
    }//GEN-LAST:event_jMenuItemEditarEscalaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {     //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPesquisarCategoriaCancelar;
    private javax.swing.JButton jButtonPesquisarCategoriaEditar;
    private javax.swing.JButton jButtonPesquisarDepartamentoCancelar;
    private javax.swing.JButton jButtonPesquisarDepartamentoEditar;
    private javax.swing.JButton jButtonPesquisarEscalaCancelar;
    private javax.swing.JButton jButtonPesquisarEscalaEditar;
    private javax.swing.JButton jButtonPesquisarFuncionarioCancelar;
    private javax.swing.JButton jButtonPesquisarFuncionarioPesquisar;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBoxCadastrarFuncionarioCategoria;
    private javax.swing.JComboBox jComboBoxCadastrarFuncionarioDepartamento;
    private javax.swing.JComboBox jComboBoxEditarEscala;
    private javax.swing.JComboBox jComboBoxEditarFuncionarioCategoria;
    private javax.swing.JComboBox jComboBoxEditarFuncionarioDepartamento;
    private javax.swing.JComboBox<String> jComboBoxPesquisarCategoriaSelecionar;
    private javax.swing.JComboBox<String> jComboBoxPesquisarDepartamentoSelecionar;
    private javax.swing.JComboBox<String> jComboBoxPesquisarEscalaSelecionar;
    private javax.swing.JComboBox jComboBoxPesquisarFuncionarioCategoria;
    private javax.swing.JDesktopPane jDesktopPanePrincipal;
    private javax.swing.JInternalFrame jInternalFrameCadastrarCategoria;
    private javax.swing.JInternalFrame jInternalFrameCadastrarDepartamento;
    private javax.swing.JInternalFrame jInternalFrameCadastrarEscala;
    private javax.swing.JInternalFrame jInternalFrameCadastrarFuncionario;
    private javax.swing.JInternalFrame jInternalFrameEditarCategoria;
    private javax.swing.JInternalFrame jInternalFrameEditarDepartamento;
    private javax.swing.JInternalFrame jInternalFrameEditarFuncionario;
    private javax.swing.JInternalFrame jInternalFramePesquisarCategoria;
    private javax.swing.JInternalFrame jInternalFramePesquisarDepartamento;
    private javax.swing.JInternalFrame jInternalFramePesquisarEscala;
    private javax.swing.JInternalFrame jInternalFramePesquisarFuncionario;
    private javax.swing.JInternalFrame jInternalFrameVisualizarCadastro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemCadastrarCategoria;
    private javax.swing.JMenuItem jMenuItemCadastrarDepartamento;
    private javax.swing.JMenuItem jMenuItemCadastrarEscala;
    private javax.swing.JMenuItem jMenuItemCadastrarFuncionario;
    private javax.swing.JMenuItem jMenuItemDesligarFuncionario;
    private javax.swing.JMenuItem jMenuItemEditarCategoria;
    private javax.swing.JMenuItem jMenuItemEditarDepartamento;
    private javax.swing.JMenuItem jMenuItemEditarEscala;
    private javax.swing.JMenuItem jMenuItemEditarFuncionario;
    private javax.swing.JMenuItem jMenuItemListarFuncionariosGeral;
    private javax.swing.JMenuItem jMenuItemListarFuncionariosPorCategoria;
    private javax.swing.JMenuItem jMenuItemListarFuncionariosPorDepartamento;
    private javax.swing.JMenuItem jMenuItemListarFuncionariosPorIdade;
    private javax.swing.JMenuItem jMenuItemRelatorioDiario;
    private javax.swing.JMenuItem jMenuItemRelatorioMensal;
    private javax.swing.JMenuItem jMenuItemRelatorioSemanal;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JSpinner jSpinnerHorasTrabalhadas;
    private javax.swing.JTextField jTextFieldCadastrarCargo;
    private javax.swing.JTextField jTextFieldCadastrarDepartamento;
    private javax.swing.JTextField jTextFieldCadastrarEscala;
    private javax.swing.JTextField jTextFieldCadastrarFuncionarioCpf;
    private javax.swing.JTextField jTextFieldCadastrarFuncionarioDataAdmissao;
    private javax.swing.JTextField jTextFieldCadastrarFuncionarioNome;
    private javax.swing.JTextField jTextFieldCadastrarFuncionarioTelefone;
    private javax.swing.JTextField jTextFieldEditarCargo;
    private javax.swing.JTextField jTextFieldEditarDepartamento;
    private javax.swing.JTextField jTextFieldEditarFuncionarioCpf;
    private javax.swing.JTextField jTextFieldEditarFuncionarioDataAdmissao;
    private javax.swing.JTextField jTextFieldEditarFuncionarioNome;
    private javax.swing.JTextField jTextFieldEditarFuncionarioTelefone;
    private javax.swing.JTextField jTextFieldPesquisarFuncionarioCpf;
    private javax.swing.JTextField jTextFieldPesquisarFuncionarioNome;
    private javax.swing.JToggleButton jToggleButtonCadastrarCategoria;
    private javax.swing.JToggleButton jToggleButtonCadastrarDepartamento;
    private javax.swing.JToggleButton jToggleButtonCadastrarEscala;
    private javax.swing.JToggleButton jToggleButtonCadastrarFuncionarioCadastrar;
    private javax.swing.JToggleButton jToggleButtonCadastrarFuncionarioCancelar;
    private javax.swing.JToggleButton jToggleButtonCancelarCadastrarCategoria;
    private javax.swing.JToggleButton jToggleButtonCancelarCadastrarDepartamento;
    private javax.swing.JToggleButton jToggleButtonCancelarCadastrarEscala;
    private javax.swing.JToggleButton jToggleButtonCancelarEditarCategoriaCancelar;
    private javax.swing.JToggleButton jToggleButtonCancelarEditarDepartamentoCancelar;
    private javax.swing.JToggleButton jToggleButtonEditarCategoriaCadastrar;
    private javax.swing.JToggleButton jToggleButtonEditarDepartamentoCadastrar;
    private javax.swing.JToggleButton jToggleButtonEditarFuncionarioCadastrar;
    private javax.swing.JToggleButton jToggleButtonEditarFuncionarioCancelar;
    // End of variables declaration//GEN-END:variables
}
